### ISSUE TITLE
Confusing first block of notebook

### ISSUE THREAD

**Issue by JohnGiorgi** [gnes-ai/demo-gnes-flow#2]
I noticed several issues with the notebook,

1. The first set of instructions is rather confusing. Are we meant to copy/paste the bash commands into our shell? They are formatted as markdown and so they aren't executable in the notebook. 
2. I had to make the following changes 
- change `'/tmp/gnes-flow-demo'` to `'tmp/gnes-flow-demo'` (otherwise a directory was created under my user directory).
- swap all mentions of `${TEST_WORKDIR}` for `$TEST_WORKDIR` (otherwise the brackets where interested in the shell literally).
- add the `-p` flag to the `mkdir` command (otherwise an error is returned about `'tmp'` not existing).

If these are real issues and not just me misunderstanding I would be happy to open a quick PR?

**Comment by only-yao** [comment]
Have you encountered this error

`I:CLIClient:[bas:__i:115]:setting up grpc insecure channel...
I:CLIClient:[bas:__i:124]:waiting channel to be ready...
`
It's going to stay right here
